#!/bin/bash
# Deploy script for Alastair

echo "Building project..."
npm run build

echo ""
echo "============================================"
echo "Deploy to Netlify using one of these methods:"
echo ""
echo "METHOD 1 - Netlify CLI (Recommended):"
echo "  1. npm install -g netlify-cli"
echo "  2. netlify login"
echo "  3. netlify deploy --prod --dir=dist"
echo ""
echo "METHOD 2 - Drag & Drop:"
echo "  1. Go to https://app.netlify.com/drop"
echo "  2. Drag the 'dist' folder from this project"
echo "  3. Your site will be live instantly!"
echo ""
echo "METHOD 3 - Git Integration:"
echo "  1. Push this repo to GitHub"
echo "  2. Connect repo at https://app.netlify.com"
echo "  3. Build settings auto-detect from netlify.toml"
echo ""
echo "AFTER DEPLOYMENT - Set Environment Variables:"
echo "  1. Go to Site Settings → Environment Variables"
echo "  2. Add: REDIS_URL=your-upstash-redis-url"
echo ""
echo "Get Upstash Redis URL: https://upstash.com"
echo "============================================"
