[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://alistair1001.netlify.app/.netlify/functions/api"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
